### PR TITLE
Fix the "Refactor RemoteGdbDebuggerPage.java" commit

### PR DESCRIPTION
**Pull request by EvgeniyaKatunina**

### CODE REVIEW

**Comment by anthony-kolesov** [comment]
s/for launching/to select/

**Comment by anthony-kolesov** [comment]
It is better to include commit title along its short hash, because hashes may changed during rebase.
There is already no commit c8ff6ee :)

**Comment by anthony-kolesov** [comment]
In commit descriptions/titles, please, refer to classes instead of files, so s/RemoteGdbDebuggerPage.java/RemoteGdbDebuggerPage/.

**Comment by EvgeniyaKatunina** [comment]
Fixed.

**Pull request merged**
